#!/usr/bin/env bash

selected="$(ps -a -u "$USER" | \
            fzf --header='Select process to kill:' \
                --height=40% \
                --reverse \
                --multi \
                --ansi \
                --preview-window='right:60%'
                --preview='echo {} | awk '\''{print $1}'\'' | xargs -I{} ps -p {} -o pid,user,%cpu,%mem,vsz,rss,tty,stat,start,time,command' \
                --bind='enter:execute(echo {} | awk '\'"{print $1}"\'' | xargs -I{} kill -9 {})')"

if [[ -n "$selected" ]]; then
    answer="$(echo -e "Yes\nNo" | \
              fzf --header='Confirm kill selected process?' \
                  --height=20% \
                  --reverse \
                  --ansi \
                  --expect='yes' \
                  --expect='no')"
    if [[ "$answer" == "yes" ]]; then
        pids="$(echo "$selected" | awk '{print $1}')"
        for pid in $pids; do
            kill -9 "$pid"
        done
    fi
fi

exit 0