#!/usr/bin/env bash

# Upload and transfer all types of file (max 5gb)
if tty -s; then
  file="$1"
  file_name=$(basename "$file")
  if [ ! -e "$file" ]; then
    echo "$file: No such file or directory"
    return 1
  fi
  if [ -d "$file" ]; then
    file_name="$file_name.zip"
    (cd "$file" && zip -r -q - .) | curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name" | tee /dev/null | tr -d '\n'
  else
    cat "$file" | curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name" | tee /dev/null | tr -d '\n'
  fi
else
  file_name=$1
  curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name" | tee /dev/null | tr -d '\n'
fi