#!/usr/bin/bash
#
# name: Control audio
# keywords: audio
# icon: audio-volume-overamplified-symbolic
# dependencies: rofi pactl playerctl notify-send

declare -A audio_controls=(
    ["⏯️ Play/pause"]="play-pause"
    ["⏮️ Previous"]="previous"
    ["⏭️ Next"]="next"
    ["🔇 Mute/unmute"]="toggle-mute"
    ["🔊 Set volume"]="set-volume"
)

selected=$(printf '%s\n' "${!audio_controls[@]}" | rofi -dmenu -i -p "Audio controls:")

if [[ -n "${selected}" ]]; then
    case $selected in
        "🔇 Mute/unmute")
            mute_status=$(pactl list sinks | grep "Mute:" | cut -d ' ' -f2)
            if [[ "$mute_status" == "yes" ]]; then
                pactl set-sink-mute @DEFAULT_SINK@ 0
            else
                pactl set-sink-mute @DEFAULT_SINK@ 1
            fi
            ;;
        "🔊 Set volume")
            volume=$(rofi -dmenu -i -p "Enter volume level (0-100):")
            if [[ "$volume" =~ ^[0-9]+$ && $volume -ge 0 && $volume -le 100 ]]; then
                pactl set-sink-volume @DEFAULT_SINK@ "$volume"%
            else
                notify-send "Invalid volume level!"
            fi
            ;;
        *)
            playerctl "${audio_controls[$selected]}"
            ;;
    esac
fi
