#!/usr/bin/bash
#
# name: Kill process by port
# keywords: kill port
# icon: process-stop-symbolic

port="$(rofi -dmenu -i -p "Enter port number to kill process")"

if ! [[ "$port" =~ ^[0-9]+$ ]]; then
    echo "Invalid input. Please enter a valid port number." >&2
    exit 1
fi

pid="$(lsof -t -i:$port)"

if [[ -z "$pid" ]]; then
    notify-send "No process found running on port $port."
    exit 1
fi

selected="$(ps -p $pid -o pid,user,%cpu,%mem,vsz,rss,tty,stat,start,time,command | \
            sed '1d' | \
            rofi -dmenu -i -p "Process running on port $port: " \
            awk '{print $1" "$2}')"

if [[ ! -z "$selected" ]]; then
    answer="$(echo -e "Yes\nNo" | \
              rofi -dmenu -i -p "$selected will be killed, are you sure?")"
    if [[ "$answer" == "Yes" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"
        kill -9 "$selpid"
    fi
fi

exit 0
