#!/usr/bin/bash
#
# name: Open last screenshot
# keywords: last screen screenshot
# icon: accessories-screenshot-symbolic

screenshotDir=$HOME/Pictures/screenshots

xdg-open $screenshotDir/"$(ls -t $screenshotDir | head -1)"
