#!/usr/bin/bash
#
# name: Scripts & commands
# keywords: scripts audio screenshot sh script list rofi pactl playerctl gnome screenshot commands emoji
# icon: utilities-terminal-symbolic 

screenshotsDir="$HOME/Pictures/screenshots"
scripts_path="$HOME/.local/share/pop-launcher/scripts/"

declare -A commands=(
    ["💡 Yeelight: Toggle lights"]="/home/asaday/.cargo/bin/yeelight-cli 192.168.1.20 toggle"
    ["🔇 Audio: Mute/unmute"]="pactl set-sink-mute @DEFAULT_SINK@ toggle"
    ["🔊 Audio: Set volume"]="volume"
    ["⏯️  Audio: Play/pause"]="playerctl play-pause"
    ["⏮️  Audio: Previous"]="playerctl previous"
    ["⏭️  Audio: Next"]="playerctl next"
    ["💾 Screenshot: Full screen"]="gnome-screenshot"
    ["💾 Screenshot: Select area"]="gnome-screenshot -a"
    ["💾 Screenshot: Current window"]="gnome-screenshot --window"
    ["💾 Screenshot: Open last screenshot"]="xdg-open $screenshotsDir/'$(ls -t $screenshotsDir | head -1)'"
    ["💾 Screenshot: Show folder"]="xdg-open $screenshotsDir"
)

show_commands_menu() {
    prompt="commands:"
    readarray -t scripts_array < <(find "$scripts_path"/* -maxdepth 1 -type f -executable \
                                  -exec grep -Iq . {} \; -print | sed 's|^'"$scripts_path"'/|📜 |' | sort)

    selected=$(printf '%s\n' "${!commands[@]}" "${scripts_array[@]}" | rofi -dmenu -i -p "$prompt")

    if [ -n "$selected" ]; then
        if [[ "$selected" == 📜* ]]; then
            # Script option selected
            eval "$scripts_path/${selected#📜 }"
        else
            # Other commands selected
            case "$selected" in
                "🔊 Audio: Set volume")
                    volume=$(rofi -dmenu -i -p "Enter volume level (0-100):")
                    if [[ "$volume" =~ ^[0-9]+$ && $volume -ge 0 && $volume -le 100 ]]; then
                        pactl set-sink-volume @DEFAULT_SINK@ "$volume"%
                    else
                        notify-send "Invalid volume level!"
                    fi
                    ;;
                *)
                    eval "${commands[$selected]}"
                    ;;
            esac
        fi
    fi
}

show_commands_menu

exit 0

