#!/usr/bin/bash
#
# name: Personal remaps
# keywords: remap remaps
# icon: input-keyboard-symbolic

# Increase key speed via a rate change
xset r rate 300 50

# Left ctrl = super
# Capslock = ctrl when held down, escape when pressed alone
# Shift = parentheses when held down, shift when pressed alone
# Both shift keys together = toggle capslock
setxkbmap -option "caps:ctrl_modifier" -option "shift:both_capslock" -option "ctrl:swap_lwin_lctl"
xcape -t 500 -e '#66=Escape;Shift_L=parenleft;Shift_R=parenright'

# Map extra mouse buttons to media keys
xmodmap -e 'keycode 193 = XF86AudioPlay'
