#!/usr/bin/bash
#
# name: Personal remaps
# keywords: remap remaps
# icon: input-keyboard-symbolic

# Increase key speed via a rate change
xset r rate 300 50

# Map capslock to ctrl, left ctrl to super and both shift keys together toggle capslock
setxkbmap -option "caps:ctrl_modifier" -option "shift:both_capslock" -option "ctrl:swap_lwin_lctl"

# But when it's pressed only once, treat it as escape
xcape -e '#66=Escape'
