#!/usr/bin/env bash
#
# name: System actions
# keywords: system actions
# icon: computer-symbolic

OPTIONS="Enter BIOS\nLock Screen\nLog Out\nRestart\nPower Off\nSuspend"

# Check if the current session is a GNOME session
is_gnome() {
  command -v dbus-send >/dev/null && \
    command -v gnome-session-quit >/dev/null && \
    dbus-send --print-reply --dest=org.gnome.Shell /org/gnome/Shell org.freedesktop.DBus.Properties.Get string:org.gnome.Shell string:ShellVersion >/dev/null 2>&1
}

# Run the selected action
run_action() {
    case $1 in
        "Enter BIOS")
            systemctl reboot --firmware-setup
            ;;
        "Lock Screen")
            xdg-screensaver lock
            ;;
        "Log Out")
            if is_gnome; then
              gnome-session-quit --logout
            elif command -v loginctl >/dev/null; then
              loginctl terminate-user "${USER}"
            fi
            ;;
        "Restart")
            if is_gnome; then
              gnome-session-quit --reboot
            elif command -v systemctl >/dev/null; then
              systemctl reboot
            fi
            ;;
        "Power Off")
            if is_gnome; then
              gnome-session-quit --power-off
            elif command -v systemctl >/dev/null; then
              systemctl poweroff
            fi
            ;;
        "Suspend")
            systemctl suspend
            ;;
        *)
            notify-send "Invalid option selected"
            ;;
    esac
}

# Prompt the user to choose an option and run the selected action
selected=$(echo -e "${OPTIONS}" | rofi -dmenu -i -p "Choose an action:")
run_action "${selected}"

