#!/usr/bin/bash
#
# name: Toggle dark mode
# keywords: dark toggle
# icon: weather-clear-night-symbolic

current_theme=$(gsettings get org.gnome.desktop.interface gtk-theme)

if echo "$current_theme" | grep -q 'dark'; then
    color_scheme='prefer-light'
    editor_scheme='pop-light'
    gtk_theme='Pop'
    icon_theme='Papirus-Light'
else
    color_scheme='prefer-dark'
    editor_scheme='pop-dark'
    gtk_theme='Pop-dark'
    icon_theme='Papirus-Dark'
fi

gsettings set org.gnome.desktop.interface color-scheme $color_scheme
gsettings set org.gnome.gedit.preferences.editor scheme $editor_scheme
gsettings set org.gnome.desktop.interface gtk-theme $gtk_theme
gsettings set org.gnome.desktop.interface icon-theme $icon_theme
